enableFlowLogs: false
# gatewayAddress: 10.10.1.1
ipCidrRange: 10.100.2.0/28
logConfig:
  aggregationInterval: INTERVAL_5_SEC
  enable: true
  flowSampling: 0.5
  metadata: INCLUDE_ALL_METADATA
name: hpc-1-private-2
network: https://www.googleapis.com/compute/v1/projects/lab-gke-se/global/networks/hpc-1
privateIpGoogleAccess: true
privateIpv6GoogleAccess: DISABLE_GOOGLE_ACCESS
purpose: PRIVATE
region: https://www.googleapis.com/compute/v1/projects/lab-gke-se/regions/us-east4

